// Seed data generated relative to today's date so stale flags and
// event dates always look realistic regardless of when the demo is run.

export function generateSeedLeads() {
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  function daysAgo(n) {
    const d = new Date(today);
    d.setDate(d.getDate() - n);
    return d.toISOString().split('T')[0];
  }

  function daysAhead(n) {
    const d = new Date(today);
    d.setDate(d.getDate() + n);
    return d.toISOString().split('T')[0];
  }

  function isoAgo(n) {
    const d = new Date(today);
    d.setDate(d.getDate() - n);
    return d.toISOString();
  }

  // Generate a timestamped note: daysBack days ago at a given hour
  function note(id, text, daysBack, hours = 10, minutes = 0) {
    const d = new Date(today);
    d.setDate(d.getDate() - daysBack);
    d.setHours(hours, minutes, 0, 0);
    return { id, text, created_at: d.toISOString() };
  }

  return [
    // 1 — Signed wedding, exclusivity_chosen, full post-sig checklist
    {
      id: '1',
      name: 'Emily & Carter Stone',
      email: 'emily.stone@email.com',
      phone: '(512) 555-0101',
      phone_given: true,
      lead_source: 'referral',
      lead_type: 'wedding',
      event_date: daysAhead(83),
      guest_count: 175,
      budget_band: '30k_50k',
      dates_flexible: false,
      lodging_needed: true,
      spaces_requested: 'Main Pavilion, Garden Terrace',
      add_ons: 'Floral arrangements, Photo booth',
      wants_tour_only: false,
      guide_assigned: 'tiffany',
      tour_date: null,
      availability_confirmed: true,
      proposal_edit_count: 2,
      exclusivity_chosen: true,
      exclusivity_marked: false,
      notes: [
        note('1_1', 'Referral from the Morrison wedding in March. Emily reached out directly — very warm lead.', 45, 9, 15),
        note('1_2', 'First call went great. They want the Main Pavilion + Garden Terrace combo. All-inclusive package. Carter is flexible on timing, Emily has a firm date.', 38, 14, 30),
        note('1_3', 'Venue walk-through completed. Both loved it. Tiffany building proposal now. Confirmed lodging for 20 guests.', 30, 11, 0),
        note('1_4', 'Proposal v1 sent. They came back with two minor revisions — bar package and florals budget. Sent v2 same day.', 22, 16, 45),
        note('1_5', 'Contract signed! Exclusivity confirmed for Sept 12. Deposit received. Posting to Google Cal today.', 10, 10, 0),
        note('1_6', 'Checked in with Emily. Very happy. Asked about upgrading the photo booth package — passed to Tiffany.', 1, 15, 20),
      ],
      last_contact_date: daysAgo(1),
      status: 'Signed',
      created_at: isoAgo(45),
      checklist: {
        invoice_sent: true,
        coordinator_notified: true,
        catering_notified: true,
        front_desk_notified: true,
        confirmation_email: false,
        exclusivity_calendar: false,
        exclusivity_cloudbeds: false,
      },
    },
    // 2 — Wedding, Proposal Sent → shows property tour reminder
    {
      id: '2',
      name: 'The Harrington Wedding',
      email: 'victoria.harrington@gmail.com',
      phone: '(512) 555-0202',
      phone_given: true,
      lead_source: 'tripleseat',
      lead_type: 'wedding',
      event_date: daysAhead(119),
      guest_count: 120,
      budget_band: '20k_30k',
      dates_flexible: true,
      lodging_needed: true,
      spaces_requested: 'Grand Ballroom',
      add_ons: 'DJ, Catering upgrade',
      wants_tour_only: false,
      guide_assigned: 'tiffany',
      tour_date: null,
      availability_confirmed: true,
      proposal_edit_count: 1,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('2_1', 'Website inquiry. Victoria is the POC — fiancé is less involved. Grand Ballroom preferred. Wants DJ and upgraded catering.', 30, 9, 0),
        note('2_2', 'Call with Victoria — she loved the proposal overall but asked for the full bar package to be added and a breakdown of the catering tiers. Will revise.', 15, 14, 0),
        note('2_3', 'Sent revised proposal v2 with bar package and catering breakdown. Victoria said she needs a week to discuss with family. Need to schedule site visit before close.', 2, 11, 30),
      ],
      last_contact_date: daysAgo(2),
      status: 'Proposal Sent',
      created_at: isoAgo(30),
      checklist: null,
    },
    // 3 — Wedding, Proposal Building
    {
      id: '3',
      name: 'Rachel & Owen Torres',
      email: 'rachel.torres@outlook.com',
      phone: '(737) 555-0303',
      phone_given: false,
      lead_source: 'direct_email',
      lead_type: 'wedding',
      event_date: daysAhead(139),
      guest_count: 95,
      budget_band: '30k_50k',
      dates_flexible: false,
      lodging_needed: false,
      spaces_requested: 'Chapel + Outdoor Terrace',
      add_ons: 'Catering, Florals',
      wants_tour_only: false,
      guide_assigned: 'serena',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('3_1', 'Direct email inquiry with very detailed requirements. They want custom bistro lighting on the Outdoor Terrace and a specific floral palette. Budget is firm at $30–50k range.', 20, 10, 0),
        note('3_2', 'Intro call with Rachel. Owen prefers email. She confirmed no lodging needed — most guests are local. Serena building proposal. Checking Cloudbeds for Nov 7 availability.', 12, 15, 30),
        note('3_3', 'Availability confirmed for Nov 7 — need to update the lead. Working on proposal draft now.', 1, 9, 45),
      ],
      last_contact_date: daysAgo(1),
      status: 'Proposal Building',
      created_at: isoAgo(20),
      checklist: null,
    },
    // 4 — Corporate, Contract Sent, $50k+
    {
      id: '4',
      name: 'Meridian Health Systems',
      email: 'events@meridianhealthtx.com',
      phone: '(512) 555-0404',
      phone_given: true,
      lead_source: 'referral',
      lead_type: 'corporate',
      event_date: daysAhead(62),
      guest_count: 250,
      budget_band: '50k_plus',
      dates_flexible: false,
      lodging_needed: true,
      spaces_requested: 'Conference Center, Main Hall',
      add_ons: 'AV package, Catering, Breakout rooms',
      wants_tour_only: false,
      guide_assigned: 'sebastian',
      tour_date: null,
      availability_confirmed: true,
      proposal_edit_count: 5,
      exclusivity_chosen: true,
      exclusivity_marked: false,
      notes: [
        note('4_1', '5th year with us — relationship managed by Sebastian. Annual leadership retreat, 250 attendees. Contact is Janet Flores, Events Manager.', 40, 9, 0),
        note('4_2', 'Requirements call. They want upgraded AV this year — hybrid setup for remote attendees. Full breakout room configuration needed. Dates are firm: Aug 22–24.', 32, 13, 0),
        note('4_3', 'Sent proposal v1. Janet came back quickly — they want to add a dedicated tech support person on-site and adjust the catering to a plated dinner format.', 24, 10, 30),
        note('4_4', 'Proposal v3 approved by events team. Now going to legal for contract review. Exclusivity expected.', 14, 14, 0),
        note('4_5', 'Contract sent to legal. Janet says they usually return within 5–7 business days. Following up next week.', 5, 11, 0),
        note('4_6', 'Touched base with Janet — contract in final review. Should have it back by end of week.', 1, 10, 15),
      ],
      last_contact_date: daysAgo(1),
      status: 'Contract Sent',
      created_at: isoAgo(40),
      checklist: null,
    },
    // 5 — Corporate, Proposal Building, edit_count = 4
    {
      id: '5',
      name: 'Blue Ridge Tech Summit',
      email: 'janna.porter@blueridgetech.io',
      phone: '(512) 555-0505',
      phone_given: false,
      lead_source: 'ad',
      lead_type: 'corporate',
      event_date: daysAhead(101),
      guest_count: 180,
      budget_band: '30k_50k',
      dates_flexible: true,
      lodging_needed: true,
      spaces_requested: 'Innovation Pavilion',
      add_ons: 'Catering, Live streaming setup',
      wants_tour_only: false,
      guide_assigned: 'sebastian',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 4,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('5_1', 'Inbound from ad campaign. First-time corporate client. Janna Porter is lead contact. Annual tech summit, 180 attendees, Innovation Pavilion.', 35, 9, 30),
        note('5_2', 'Proposal v1 sent. Client came back — budget is tighter than anticipated. Need to reduce catering scope and adjust AV package.', 28, 14, 0),
        note('5_3', 'Revision 2 sent. New feedback: they want to add live streaming but trim catering further. Also shifting session layout to theater-style.', 21, 11, 0),
        note('5_4', 'Revision 3 sent. Janna is happy with catering now but the streaming vendor changed scope — need to re-quote. 4th revision incoming. Timeline ~3–4 weeks total is on track.', 14, 10, 0),
        note('5_5', 'Working on revision 4. Streaming vendor quote received. Should have this out by EOD tomorrow.', 2, 16, 0),
      ],
      last_contact_date: daysAgo(2),
      status: 'Proposal Building',
      created_at: isoAgo(35),
      checklist: null,
    },
    // 6 — Corporate, Nurturing, long planning horizon
    {
      id: '6',
      name: 'Summit Financial Group',
      email: 'admin@summitfgroupevents.com',
      phone: '(214) 555-0606',
      phone_given: false,
      lead_source: 'direct_email',
      lead_type: 'corporate',
      event_date: daysAhead(238),
      guest_count: 80,
      budget_band: '10k_20k',
      dates_flexible: true,
      lodging_needed: false,
      spaces_requested: 'Board Room, Garden Patio',
      add_ons: 'Catering',
      wants_tour_only: false,
      guide_assigned: 'unassigned',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('6_1', 'Annual shareholder dinner, 80 guests. Long planning horizon — event is in Feb next year. Board Room + Garden Patio. Keep warm with quarterly check-ins.', 15, 10, 0),
        note('6_2', 'Sent a quarterly check-in email. No reply yet. Will try again in 3 weeks.', 3, 11, 0),
      ],
      last_contact_date: daysAgo(3),
      status: 'Nurturing',
      created_at: isoAgo(15),
      checklist: null,
    },
    // 7 — Wedding, New, phone_given = true → "Call + text now" badge
    {
      id: '7',
      name: 'Sophia & Daniel Park',
      email: 'sophia.park.wedding@gmail.com',
      phone: '(512) 555-0707',
      phone_given: true,
      lead_source: 'tripleseat',
      lead_type: 'wedding',
      event_date: daysAhead(308),
      guest_count: 110,
      budget_band: '20k_30k',
      dates_flexible: true,
      lodging_needed: true,
      spaces_requested: 'Garden Ceremony + Indoor Reception',
      add_ons: 'Photo booth, Florals',
      wants_tour_only: false,
      guide_assigned: 'unassigned',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('7_1', 'New inquiry via website form. Phone number provided — high intent signal. Call them today.', 0, 8, 45),
      ],
      last_contact_date: daysAgo(0),
      status: 'New',
      created_at: isoAgo(0),
      checklist: null,
    },
    // 8 — Auto-disqualified: wedding, 45 guests, under_10k
    {
      id: '8',
      name: 'Chloe & Ben Waters',
      email: 'chloebwedding@gmail.com',
      phone: '',
      phone_given: false,
      lead_source: 'website_form',
      lead_type: 'wedding',
      event_date: daysAhead(182),
      guest_count: 45,
      budget_band: 'under_10k',
      dates_flexible: false,
      lodging_needed: false,
      spaces_requested: 'Small chapel',
      add_ons: '',
      wants_tour_only: false,
      guide_assigned: 'unassigned',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('8_1', 'Auto-disqualified at intake. Wedding under 75 guests with budget under $30k. Threshold is a placeholder — confirm with Tiffany and Mike before go-live.', 5, 9, 0),
      ],
      last_contact_date: daysAgo(4),
      status: 'Disqualified',
      created_at: isoAgo(5),
      checklist: null,
    },
    // 9 — Wedding, Call Scheduled, STALE (8 days)
    {
      id: '9',
      name: 'Alex & Jordan Kim',
      email: 'jordan.kim@email.com',
      phone: '(512) 555-0909',
      phone_given: true,
      lead_source: 'phone_call',
      lead_type: 'wedding',
      event_date: daysAhead(132),
      guest_count: 80,
      budget_band: '20k_30k',
      dates_flexible: true,
      lodging_needed: false,
      spaces_requested: 'Outdoor Amphitheater',
      add_ons: 'Lighting package',
      wants_tour_only: false,
      guide_assigned: 'serena',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('9_1', 'Inbound phone call. Jordan is main contact. Outdoor Amphitheater for Oct 31 — Halloween wedding! Lighting package is important to them.', 18, 14, 0),
        note('9_2', 'Scheduled a discovery call for last Thursday. Jordan confirmed via email but then went silent. No response to follow-up text. Needs follow-up ASAP.', 8, 10, 0),
      ],
      last_contact_date: daysAgo(8),
      status: 'Call Scheduled',
      created_at: isoAgo(18),
      checklist: null,
    },
    // 10 — Corporate, Call Scheduled, recent
    {
      id: '10',
      name: 'Pinnacle Events Group',
      email: 'diana.reyes@pinnacleevents.com',
      phone: '(512) 555-1010',
      phone_given: true,
      lead_source: 'referral',
      lead_type: 'corporate',
      event_date: daysAhead(147),
      guest_count: 150,
      budget_band: '20k_30k',
      dates_flexible: false,
      lodging_needed: true,
      spaces_requested: 'Main Conference Hall',
      add_ons: 'AV package, Catering',
      wants_tour_only: false,
      guide_assigned: 'tiffany',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('10_1', 'Referral from Cascade Valley. Annual awards dinner, 150 guests. Diana Reyes is the decision maker. Call set for Wednesday.', 7, 10, 0),
        note('10_2', 'Diana confirmed the call. She mentioned they have a $20–30k budget and Nov 15 is firm.', 1, 16, 0),
      ],
      last_contact_date: daysAgo(1),
      status: 'Call Scheduled',
      created_at: isoAgo(7),
      checklist: null,
    },
    // 11 — Wedding, Tour Scheduled, guide: tiffany
    {
      id: '11',
      name: 'Marcus & Valentina Cruz',
      email: 'valentina.cruz.events@gmail.com',
      phone: '(737) 555-1111',
      phone_given: true,
      lead_source: 'website_form',
      lead_type: 'wedding',
      event_date: daysAhead(70),
      guest_count: 130,
      budget_band: '20k_30k',
      dates_flexible: false,
      lodging_needed: true,
      spaces_requested: 'Chapel, Garden Walk',
      add_ons: 'Florals, Catering',
      wants_tour_only: true,
      guide_assigned: 'tiffany',
      tour_date: daysAhead(7),
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('11_1', 'Website inquiry. They want to see the space in person before committing. Valentina is very visual — photos aren\'t enough. Tour-first track makes sense here.', 10, 9, 0),
        note('11_2', 'Called Valentina. She loved the website photos. Scheduled a tour with Tiffany for next week. Marcus will join. Chapel + Garden Walk is the primary interest.', 2, 15, 30),
      ],
      last_contact_date: daysAgo(2),
      status: 'Tour Scheduled',
      created_at: isoAgo(10),
      checklist: null,
    },
    // 12 — Other, New, STALE (7 days)
    {
      id: '12',
      name: 'Lauren & James Walsh',
      email: 'lauren.walsh@hotmail.com',
      phone: '(214) 555-1212',
      phone_given: false,
      lead_source: 'direct_email',
      lead_type: 'other',
      event_date: daysAhead(76),
      guest_count: 60,
      budget_band: '10k_20k',
      dates_flexible: true,
      lodging_needed: false,
      spaces_requested: 'Event lawn',
      add_ons: '',
      wants_tour_only: false,
      guide_assigned: 'unassigned',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('12_1', "Birthday celebration inquiry for 60 guests. Event lawn preferred. Haven't responded to follow-up emails sent on intake day.", 9, 11, 0),
        note('12_2', 'Second follow-up sent. Still no reply. Stale — needs manual outreach.', 7, 10, 0),
      ],
      last_contact_date: daysAgo(7),
      status: 'New',
      created_at: isoAgo(9),
      checklist: null,
    },
    // 13 — Wedding, Nurturing, STALE (10 days)
    {
      id: '13',
      name: 'Stephanie & Chris Monroe',
      email: 'stephanie.monroe.wed@gmail.com',
      phone: '(512) 555-1313',
      phone_given: true,
      lead_source: 'ad',
      lead_type: 'wedding',
      event_date: daysAhead(323),
      guest_count: 90,
      budget_band: '10k_20k',
      dates_flexible: true,
      lodging_needed: true,
      spaces_requested: 'Barn + Outdoor Terrace',
      add_ons: 'DJ, Florals',
      wants_tour_only: false,
      guide_assigned: 'unassigned',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('13_1', 'Ad lead. Interested but budget is tight at $10–20k. Long horizon (May next year). Putting in nurture sequence.', 25, 10, 0),
        note('13_2', 'Sent value touchpoint email — "5 reasons to book early." No response yet.', 10, 9, 0),
      ],
      last_contact_date: daysAgo(10),
      status: 'Nurturing',
      created_at: isoAgo(25),
      checklist: null,
    },
    // 14 — Corporate, Proposal Sent
    {
      id: '14',
      name: 'Cascade Valley Enterprises',
      email: 'hr@cascadevalleyco.com',
      phone: '(512) 555-1414',
      phone_given: false,
      lead_source: 'referral',
      lead_type: 'corporate',
      event_date: daysAhead(109),
      guest_count: 200,
      budget_band: '30k_50k',
      dates_flexible: false,
      lodging_needed: true,
      spaces_requested: 'Full venue buyout',
      add_ons: 'Full catering, AV, Overnight lodging',
      wants_tour_only: false,
      guide_assigned: 'serena',
      tour_date: null,
      availability_confirmed: true,
      proposal_edit_count: 3,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('14_1', 'Full venue buyout for company retreat. 200 guests. Oct 8 is firm. Referred by Pinnacle Events. Serena is lead guide.', 28, 9, 0),
        note('14_2', 'First two proposal revisions quick — mostly AV scope changes. Third revision addressed overnight lodging configuration. Proposal v3 sent today.', 14, 14, 0),
        note('14_3', 'HR contact confirmed receipt of v3. Taking it to their leadership team for final sign-off. Expect feedback within a week.', 2, 11, 0),
      ],
      last_contact_date: daysAgo(2),
      status: 'Proposal Sent',
      created_at: isoAgo(28),
      checklist: null,
    },
    // 15 — Wedding, Goes Cold
    {
      id: '15',
      name: 'Amanda & Tyler Ross',
      email: 'amanda.ross.wed@gmail.com',
      phone: '',
      phone_given: false,
      lead_source: 'website_form',
      lead_type: 'wedding',
      event_date: daysAhead(28),
      guest_count: 60,
      budget_band: '10k_20k',
      dates_flexible: false,
      lodging_needed: false,
      spaces_requested: 'Garden Ceremony',
      add_ons: '',
      wants_tour_only: false,
      guide_assigned: 'unassigned',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('15_1', 'Website inquiry for Garden Ceremony, 60 guests. Budget on the low end.', 45, 10, 0),
        note('15_2', 'Stopped responding after the initial intro call. Tried email and phone — no reply. Likely went with another venue.', 20, 14, 0),
      ],
      last_contact_date: daysAgo(20),
      status: 'Goes Cold',
      created_at: isoAgo(45),
      checklist: null,
    },
    // 16 — Other, Lost
    {
      id: '16',
      name: 'Blake Thompson Creative',
      email: 'blake@thompsonproductions.com',
      phone: '',
      phone_given: false,
      lead_source: 'direct_email',
      lead_type: 'other',
      event_date: daysAhead(9),
      guest_count: 30,
      budget_band: 'under_10k',
      dates_flexible: false,
      lodging_needed: false,
      spaces_requested: 'Studio Space',
      add_ons: '',
      wants_tour_only: false,
      guide_assigned: 'unassigned',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('16_1', 'Budget well below our minimum. Politely declined and referred to smaller local venues. Marked as Lost.', 12, 10, 0),
      ],
      last_contact_date: daysAgo(5),
      status: 'Lost',
      created_at: isoAgo(12),
      checklist: null,
    },
    // 17 — Wedding, Contract Sent, high value
    {
      id: '17',
      name: 'Nicole & Ryan Hartley',
      email: 'nicole.hartley.events@gmail.com',
      phone: '(512) 555-1717',
      phone_given: true,
      lead_source: 'referral',
      lead_type: 'wedding',
      event_date: daysAhead(167),
      guest_count: 200,
      budget_band: '50k_plus',
      dates_flexible: false,
      lodging_needed: true,
      spaces_requested: 'Grand Pavilion + Full grounds',
      add_ons: 'Complete package — florals, catering, DJ, photo',
      wants_tour_only: false,
      guide_assigned: 'tiffany',
      tour_date: null,
      availability_confirmed: true,
      proposal_edit_count: 2,
      exclusivity_chosen: true,
      exclusivity_marked: false,
      notes: [
        note('17_1', 'Largest wedding inquiry this year — 200 guests, full grounds, complete package. High-touch client. Tiffany is personal guide.', 50, 9, 0),
        note('17_2', 'Venue tour completed. Nicole cried — she loved the Grand Pavilion. Ryan very practical, focused on logistics. Two proposal revisions to dial in lodging capacity.', 35, 14, 0),
        note('17_3', 'Contract sent. Exclusivity included. Nicole mentioned they may want to add late-night catering — flagged for post-signing add-on conversation.', 1, 11, 30),
      ],
      last_contact_date: daysAgo(1),
      status: 'Contract Sent',
      created_at: isoAgo(50),
      checklist: null,
    },
    // 18 — Corporate, tour track, Post-Tour Follow-up
    {
      id: '18',
      name: 'Harbor Point Capital',
      email: 'events@harborpointcap.com',
      phone: '(512) 555-1818',
      phone_given: true,
      lead_source: 'phone_call',
      lead_type: 'corporate',
      event_date: daysAhead(152),
      guest_count: 120,
      budget_band: '20k_30k',
      dates_flexible: true,
      lodging_needed: true,
      spaces_requested: 'Executive Boardroom + Dining Room',
      add_ons: 'Catering, AV',
      wants_tour_only: true,
      guide_assigned: 'sebastian',
      tour_date: daysAgo(6),
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('18_1', 'Inbound phone call from Harbor Point Capital. Executive offsite, 120 attendees. Sebastian booked for tour.', 14, 10, 0),
        note('18_2', 'Tour completed with Sebastian. Very positive — the Dining Room layout impressed them. They want to take it back to the partners before committing.', 6, 16, 0),
        note('18_3', 'Follow-up email sent day after tour. They acknowledged and said decision by end of week.', 3, 10, 0),
      ],
      last_contact_date: daysAgo(3),
      status: 'Post-Tour Follow-up',
      created_at: isoAgo(14),
      checklist: null,
    },
    // 19 — Wedding, New, high value, no phone
    {
      id: '19',
      name: 'Isabella & Mason Wright',
      email: 'isawright.wedding@gmail.com',
      phone: '(512) 555-1919',
      phone_given: false,
      lead_source: 'tripleseat',
      lead_type: 'wedding',
      event_date: daysAhead(356),
      guest_count: 250,
      budget_band: '50k_plus',
      dates_flexible: false,
      lodging_needed: true,
      spaces_requested: 'Full property buyout',
      add_ons: 'All inclusive — catering, bar, florals, overnight',
      wants_tour_only: false,
      guide_assigned: 'unassigned',
      tour_date: null,
      availability_confirmed: false,
      proposal_edit_count: 0,
      exclusivity_chosen: false,
      exclusivity_marked: false,
      notes: [
        note('19_1', 'High-value new inquiry — 250 guests, full property buyout, all-inclusive. Website form submission. Assign a guide and reach out today.', 2, 8, 30),
      ],
      last_contact_date: daysAgo(2),
      status: 'New',
      created_at: isoAgo(2),
      checklist: null,
    },
    // 20 — Corporate, Signed, exclusivity fully marked
    {
      id: '20',
      name: 'Apex Technology Partners',
      email: 'kendra.mills@apextp.com',
      phone: '(512) 555-2020',
      phone_given: true,
      lead_source: 'referral',
      lead_type: 'corporate',
      event_date: daysAhead(27),
      guest_count: 300,
      budget_band: '50k_plus',
      dates_flexible: false,
      lodging_needed: true,
      spaces_requested: 'Full venue — all spaces',
      add_ons: 'Full catering, AV, Overnight lodging, Concierge services',
      wants_tour_only: false,
      guide_assigned: 'sebastian',
      tour_date: null,
      availability_confirmed: true,
      proposal_edit_count: 6,
      exclusivity_chosen: true,
      exclusivity_marked: true,
      notes: [
        note('20_1', 'Annual leadership summit — 300 attendees, full venue. Kendra Mills is the exec sponsor. Sebastian is relationship owner.', 60, 9, 0),
        note('20_2', 'Proposal went through 6 rounds over 4 weeks — typical for Apex. Major changes were concierge services scope and AV upgrade.', 35, 14, 0),
        note('20_3', 'Contract signed. Full deposit received. Exclusivity marked in Google Cal and Cloudbeds. All post-sig tasks complete.', 15, 10, 0),
        note('20_4', 'Pre-event check-in with Kendra. Everything on track. Catering confirmed, AV team arriving day before.', 1, 11, 0),
      ],
      last_contact_date: daysAgo(1),
      status: 'Signed',
      created_at: isoAgo(60),
      checklist: {
        invoice_sent: true,
        coordinator_notified: true,
        catering_notified: true,
        front_desk_notified: true,
        confirmation_email: true,
        exclusivity_calendar: true,
        exclusivity_cloudbeds: true,
      },
    },
  ];
}
